package-lock.json, package.json, src/dropTheRope.ts, src/utils/content-utils.ts, src/utils/filename-utils.ts, src/utils/folder-utils.ts, src/yarle.ts, test/data/test-twoNotesWithSameName.1.md, test/yarle.spec.ts
folders can be added instead of simple enex files, unique zettelkasten ids
=> feat: folders and unique zattels

README.md, package-lock.json, package.json, src/dropTheRope.ts, src/utils/turndown-rules/span.ts, src/utils/turndown-service.ts, src/yarle.ts, test/data/test-nospanstyle.enex, test/data/test-nospanstyle.md, test/yarle.spec.ts
=> fix: bug53, code cleaned

package.json, src/YarleOptions.ts, src/convert-html-to-md.ts, src/dropTheRope.ts, src/process-node.ts, src/utils/filename-utils.ts, src/utils/note-utils.ts, src/utils/turndown-rules/wikistyle-links-rule.ts, src/yarle.ts
This is the replacement PR for #71 
This PR allows users to specify a parameter that makes yarle skip webclips.
P. S.: (same as in #71 ) It's a small fix but maybe you could also put the hacktoberfest-accepted label on this, if you accept it. Thanks! 👍
=> Feat: Skip Webclips

README.md
Also, removed the section on simple and complex notes because this has been changed in #74.
=> Fix minor grammar issues in README

README.md, src/YarleOptions.ts, src/models/TagSeparatorReplaceOptions.ts, src/models/index.ts, src/utils/content-utils.ts, src/utils/get-any-index.ts, src/utils/index.ts, src/utils/templates/apply-functions/apply-content-template.ts, src/yarle.ts, test/data/test-noteWithNestedTags.enex, test/data/test-noteWithNestedTags.md, test/data/test-noteWithNestedTagsAndSpaces.enex, test/data/test-noteWithNestedTagsAndSpaces.md, test/data/test-noteWithNestedTagsAndSpacesCustom.enex, test/data/test-noteWithNestedTagsAndSpacesCustom.md, test/yarle-tests.ts
=> feat: nested tags conversion implemented

package-lock.json, package.json, src/utils/content-utils.ts, test/utils.spec.ts
=> Revert "Set creation time of Markdown files if possible"

src/process-node.ts, src/yarle.ts
Just a small add to track processing time
=> Output processing time

.gitignore, .npmignore, dropTheRope.sh, package.json, src/triggerYarle.ts
=> fix: start script improved

src/ui/assets/js/ipc.js, src/ui/sections/config.html
closes: https://github.com/akosbalasko/yarle/issues/273
=> fix: selectboxes config feed from ui

README.md, config.json, src/YarleOptions.ts, src/dropTheRopeRunner.ts, src/ui/assets/js/dialog.js, src/ui/index.html, src/ui/index.ts, src/ui/main.ts, src/ui/sections/enex.html, src/ui/settingsMapper.ts, src/ui/store.ts, src/utils/folder-utils.ts, src/yarle.ts, test/yarle-special-cases.spec.ts, test/yarle-tests.ts
One part of the feat. request covered: https://github.com/akosbalasko/yarle/issues/292
=> feat: adding multiple enex files enabled from UI

config.json, src/ui/settingsMapper.ts
story: https://github.com/akosbalasko/yarle/issues/327
=> fix: set urlEncodeFileNamesAndLinks changes in data model

src/utils/turndown-rules/images-rule.ts
=> fix: replaceAll switched back to regex

src/dropTheRopeRunner.ts, src/ui/main.ts, src/utils/apply-links.ts
=> fix: runner executed from ui instead of just droptherope

README.md, Templates.md, package-lock.json, package.json, src/YarleOptions.ts, src/models/MetaData.ts, src/models/NoteData.ts, src/utils/content-utils.ts, src/utils/templates/apply-functions/apply-reminderdonetime-template.ts, src/utils/templates/apply-functions/apply-reminderorder-template.ts, src/utils/templates/apply-functions/apply-remindertime-template.ts, src/utils/templates/apply-functions/index.ts, src/utils/templates/checker-functions.ts, src/utils/templates/placeholders/reminderdonetime-placeholders.ts, src/utils/templates/placeholders/reminderorder-placeholders.ts, src/utils/templates/placeholders/remindertime-placeholders.ts, src/utils/templates/remove-functions/index.ts, src/utils/templates/remove-functions/remove-reminderdonetime-placeholder.ts, src/utils/templates/remove-functions/remove-reminderorder-placeholder.ts, src/utils/templates/remove-functions/remove-remindertime-placeholder.ts, src/utils/templates/templates.ts, test/data/reminder_template.templ, test/data/test - reminders title.md, test/data/test-reminder.enex, test/yarle-special-cases.spec.ts
story: https://github.com/akosbalasko/yarle/issues/348
=> feat: reminders implemented

src/utils/content-utils.ts, test/data/full_template.templ, test/data/test-old-note.enex, test/data/test-old-note.md, test/yarle-special-cases.spec.ts
story: https://github.com/akosbalasko/yarle/issues/362
=> fix: avoiding negative epoch creation dates

src/convert-html-to-md.ts, src/utils/turndown-rules/task-list-rule.ts, src/utils/turndown-service.ts, test/data/LinkedInterNotebooks/test-internotebook_links_A/Table of Contents.md, test/data/LinkedInterNotebooks/test-internotebook_links_B/Table of Contents.md, test/data/test-checklist.md, test/data/test-hugeHtml.md, test/data/test-list.enex, test/data/test-list.md, test/data/test-specialItems.md, test/data/test-sublists-invalid.enex, test/data/test-sublists-invalid.md, test/data/test-sublists-valid.md, test/data/test-sublists.md, test/data/test-webclip_article.md, test/yarle-test.ts, test/yarle-tests.ts, test/yarle.spec.ts
story: https://github.com/akosbalasko/yarle/issues/339
story: https://github.com/akosbalasko/yarle/issues/324
=> fix: extra spaces in lists

config.logseq.json, package.json
story: https://github.com/akosbalasko/yarle/issues/391
=> fix: template added

src/process-resources.ts
story: https://github.com/akosbalasko/yarle/issues/407
=> fix: timestamp added instead of human readable datetime

Notes_for_Logseq.md, README.md, config.json, config.logseq.json, package-lock.json, package.json, src/YarleOptions.ts, src/ui/sections/config.html, src/ui/settingsMapper.ts, src/utils/filename-utils.ts, test/yarle-special-cases.spec.ts, test/yarle-tests.ts, typings/unique-filename/index.d.ts
story: https://github.com/akosbalasko/yarle/issues/329
=> feat: unique unknown filename implemented

src/utils/turndown-rules/task-list-rule.ts, test/data/test-checklist.md, test/data/test-hugeHtml.md, test/data/test-sublists-invalid.md, test/data/test-sublists-multiple.md, test/data/test-sublists-valid.md, test/data/test-sublists.md
closes: https://github.com/akosbalasko/yarle/issues/420
=> fix: replacing two spaces by a single tab

Notes_for_Logseq.md, README.md, config.json, config.logseq.json, src/YarleOptions.ts, src/ui/sections/config.html, src/ui/settingsMapper.ts, src/ui/store.ts, src/utils/filename-utils.ts, src/yarle.ts, test/yarle-special-cases.spec.ts, test/yarle-tests.ts
story: https://github.com/akosbalasko/yarle/issues/424
=> feat: useZettelIdAsFilename option

src/utils/filename-utils.ts, test/data/test -note _with text only.md, test/data/test-justText-linkbreakingNote.enex, test/yarle-tests.ts
story: https://github.com/akosbalasko/yarle/issues/425
=> feat: title normalized to do not break links

src/process-tasks.ts, src/yarle.ts
fixes: https://github.com/akosbalasko/yarle/issues/434
=> fix: evernote v10 multiple tasks

src/utils/folder-utils.ts
story: https://github.com/akosbalasko/yarle/issues/428
=> fix: create resource folder for Logseq, no matter what

src/ui/assets/js/dialog.js, src/ui/renderer.js
fix: https://github.com/akosbalasko/yarle/issues/452
=> fix: prevent updating outputFormat to reinit enex or outputDir

src/utils/folder-utils.ts, test/data/test.dots.in.enex.File.Name.enex, test/data/test.dots.in.enex.File.Name.md, test/yarle-special-cases.spec.ts
story: https://github.com/akosbalasko/yarle/issues/455
=> fix: handling enex filenames containing multiple dots

config.json, config.logseq.json
story: https://github.com/akosbalasko/yarle/issues/457
=> fix: keepImageSize added to config 

src/utils/templates/match-all.ts, src/utils/templates/remove-functions/remove-placeholder.ts, test/data/template_tags_bottom.templ
story: https://www.reddit.com/r/ObsidianMD/comments/135kva0/yarle_inaccurate_parsing_of_sourceurlblock/
=> fix: remove template placeholders

src/ui/renderer.js
=> fix: boolean conversion fixed

sampleTemplate.tmpl
story: https://github.com/akosbalasko/yarle/issues/507
=> fix: dots and underscores removed

src/utils/filename-utils.ts, test/data/case-insensitive.enex, test/data/test ABC.md, test/data/test abc.1.md, test/yarle-special-cases.spec.ts
story: https://github.com/akosbalasko/yarle/issues/512
=> fix: case insensitive filenames

src/utils/filename-utils.ts, test/data/sanitize_fulltest.enex, test/data/sanitize_fulltest/title_lessthangreaterThancolonapostrophebackslashslashlinequestionstar_endOfTitle.md, test/yarle-special-cases.spec.ts
story: https://github.com/akosbalasko/yarle/issues/514
=> fix: charactermap replacement added to resource extensions as well

src/models/InternalLink.ts, src/runtime-properties.ts, src/utils/turndown-rules/internal-links-rule.ts
story: https://github.com/akosbalasko/yarle/issues/498
=> fix: support of evernote links fine tuned

src/process-resources.ts, src/utils/apply-links.ts, src/utils/content-utils.ts, src/utils/file-utils.ts, test/data/updateFileContentSafelyFile.md, test/utils.spec.ts
story: https://github.com/akosbalasko/yarle/issues/486
=> fix: implemented and tested

src/utils/turndown-rules/internal-links-rule.ts, test/data/link to telephone 202-555-0179.enex, test/data/link to telephone_ 202-555-0179.md, test/yarle-tests.ts
story: https://github.com/akosbalasko/yarle/issues/489
=> fix: tel in href fixed

src/utils/turndown-rules/underline-rule.ts, src/utils/turndown-service.ts, test/data/text styles.enex, test/data/text styles.md, test/yarle-tests.ts
story: https://github.com/akosbalasko/yarle/issues/492
=> feat: underline supported

package-lock.json, package.json
story: https://github.com/akosbalasko/yarle/issues/533
=> fix: zip-a-folder 3.0.0

src/utils/turndown-rules/internal-links-rule.ts
story: https://github.com/akosbalasko/yarle/issues/531
=> fix: getting unique name fixed

package-lock.json, package.json
fix: https://github.com/akosbalasko/yarle/issues/539
=> fix: utimes version update to work with Mac Silicon

package-lock.json, src/ui/assets/css/demo.css, src/ui/assets/js/dialog.js, src/ui/index.html, src/ui/main.js, src/ui/preload.js, src/ui/renderer.js, src/ui/store.js, src/utils/folder-utils.ts, src/yarle.ts
story: https://github.com/akosbalasko/yarle/issues/256
=> feat: config store and management

sampleTemplate.tmpl
story: https://github.com/akosbalasko/yarle/issues/560
=> fix: template made comliant with Obsidian 1.5.3

src/process-node.ts, test/data/test-link-with-images-no-size.md, test/yarle-special-cases.spec.ts
story: https://github.com/akosbalasko/yarle/issues/559
=> fix: imagesize in links

src/utils/turndown-rules/images-rule.ts, test/data/test-link-with-images.md
story: https://github.com/akosbalasko/yarle/issues/564
=> fix: escaping pipe if the link is Obsidian-style

README.md, config.json, config.logseq.json, config.tana.json, package-lock.json, src/YarleOptions.ts, src/ui/index.html, src/ui/settingsMapper.ts, src/utils/turndown-rules/div-rule.ts, src/yarle.ts, test/data/test-normal+tabbed text.enex, test/data/test-normal+tabbed text.md, test/yarle-special-cases.spec.ts
story: https://github.com/akosbalasko/yarle/issues/565
=> Feat: trimstartingtabs

src/utils/content-utils.ts
story: https://github.com/akosbalasko/yarle/issues/578
=> fix: capital cyrill

README.md, config.json, config.logseq.json, config.tana.json, package-lock.json, package.json, src/YarleOptions.ts, src/ui/index.html, src/ui/preload.js, src/ui/renderer.js, src/ui/settingsMapper.ts, src/utils/decrypt.ts, src/utils/turndown-rules/encrypt-rule.ts, src/utils/turndown-service.ts, src/yarle.ts, test/data/test-encryption.enex, test/data/test-encryption.md, test/yarle-special-cases.spec.ts
story: https://github.com/akosbalasko/yarle/issues/543
=> feat: notes decryption supported

src/utils/decrypt.ts, test/data/test-encryption-nopassword.md, test/yarle-special-cases.spec.ts
story: https://github.com/akosbalasko/yarle/issues/543
=> fix: encryption fixed

src/utils/apply-links.ts, test/data/test-guid-logseq-config.json, test/data/test-guid-logseq.enex, test/data/test-logseq-guid-pages/Note 1.md, test/data/test-logseq-guid-pages/Note 2.md, test/data/test-logseq-guid-pages/Note 3.md, test/data/test-logseq-guid-pages/Table of Contents.md, test/yarle-special-cases.spec.ts
story: https://github.com/akosbalasko/yarle/issues/586
=> fix: Evernote GUID and Note Link template placeholders in LogSeqMD

README.md, config.json, config.logseq.json, config.tana.json, package-lock.json, src/YarleOptions.ts, src/ui/index.html, src/ui/settingsMapper.ts, src/utils/content-utils.ts, src/yarle.ts, test/data/test-invalid-tags-keep.md, test/data/test-invalid-tags.enex, test/yarle-special-cases.spec.ts
=> feat: option to remove utf tags
