.github/workflows/run-tests.yaml, .nycrc, package-lock.json, package.json, test/yarle.spec.ts
Hey there
Sorry about sending a PR for something which doesn't have an open issue, but I thought you could be interested on having YARLE to work with Node 12 and  14.
As far as I could see, the issue with these versions of Node were caused by a dependency `@ronomon/utimes` which is not being used anymore (looks like `fs.utimeSync` is doing the utime work?)
I also set up a workflow on github actions to run all tests against node 10, 12 and 14, although I had to turn off coverage check. Having Github actions is also nice so it allows to have that little  badge "all tests passing" on the README file :)
Feel free to reject this PR if it doesn't make sense, I could be missing something about @ronomon/utimes. One thing I did was to run YARLE on Node 14 against all my 100+ enex notes and all …
=> Support node 12 and 14

package-lock.json, package.json, src/convert-html-to-md.ts, test/data/test-sublists-valid.enex, test/data/test-sublists-valid.md, test/data/test-sublists.enex, test/data/test-sublists.md, test/yarle.spec.ts
Fixes #60. This basically uses [this fix](https://github.com/domchristie/turndown/issues/232#issuecomment-394052373) but instead of doing it inside of turndown, we create DOM representation of the note already in yarle itself so we can use the function. Since we actually need to move nodes around, I don't see a way to use a rule for this.
I also added a test.
=> fix: indent sublists correctly

package-lock.json, package.json, src/convert-html-to-md.ts, test/data/test-specialItems.md, test/data/test-sublists-multiple.enex, test/data/test-sublists-multiple.md, test/yarle.spec.ts
This one adds another piece to the sublist fix. Given ENML like this:
```HTML
<ul>
<li>
<div>Level1</div>
<ul>
<li>
<div>Level2</div>
</li>
</ul>
</li>
<li>
<div>Level1</div>
<ul>
<li>
<div>Level2</div>
</li>
</ul>
</li>
<li>
<div>Level1</div>
<ul>
<li>
<div>Level2</div>
</li>
</ul>
</li>
</ul>
```
Turndown will generate Markdown with extra whitespace:
```md
*   Level1
*   Level2
*   Level1
*   Level2
*   Level1
*   Level2
```
Screenshot for better visibility:
This is because ENMLs `<li>`-Elements wrap their contents by `<div>`-Elements, which are Block-Level-Elements and therefore lead to unintended whitespace.
- You will notice that I had to correct one test case which also had this extra whitespace problem.
- I also added a build:watch script and added nodemon for it. I can remove …
=> fix Remove extraneous whitespace from sublists

package.json, src/dropTheRope.ts, src/utils/turndown-rules/filter-by-nodename.ts
Closes #77 
In order to make yarle usable as a command we need to do the following things:
1. Add a bin and a files key to the package.json
2. Add a shebang to dropTheRope.ts
Now we can use yarle without the need to clone the repo, install and build it first.
```sh
npm i -g  yarle-evernote-to-md
yarle  --enexSource ./in/test-pdf.enex --outputDir=./out
```
or with npx:
```sh
npx -p  yarle-evernote-to-md yarle  --enexSource ./in/test-pdf.enex --outputDir=./out
```
To test this:
```sh
npm link
yarle  --enexSource ./in/test-pdf.enex --outputDir=./out
```
=> Feat: Make it usable as a command

.gitignore, src/convert-html-to-md.ts
Closes #78 
[See MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) for the problem that innerHTML introduced here:
>If a <div>, <span>, or <noembed> node has a child text node that includes the characters (&), (<), or (>), innerHTML returns these characters as the HTML entities "&amp;", "&lt;" and "&gt;" respectively. Use Node.textContent to get a raw copy of these text nodes' contents.
Also the reason why I created an Array out of childNodes [is described here](https://github.com/microsoft/TypeScript/issues/2695).
=> Fix: Fix internal Links

src/utils/turndown-rules/code-block-rule.ts, test/data/test-noteWithCodeBlock.md, test/data/test-specialItems.md
Little fix to remove an empty line from a fenced code block.
=> Fix: Remove empty first line from fenced code blocks

README.md, package-lock.json, src/YarleOptions.ts, src/dropTheRope.ts, src/process-node.ts, src/utils/content-utils.ts, src/utils/file-utils.ts, src/utils/filename-utils.ts, src/utils/index.ts, src/yarle.ts, test/data/test-noteWithNotebookName.enex, test/data/test-noteWithNotebookName.md, test/data/test-noteWithNotebookNameAndTags.enex, test/data/test-noteWithNotebookNameAndTags.md, test/yarle.spec.ts
- Add new flag --include-notebook-name that when set includes the
basename of the enex file in the note. This is useful for keeping notes
semi-structured when using an editor such as ObsidianMD.
- Add tests for notebook name on it's own and notebook name + tags.
- Fix bug with yarleOptions causing tests to keep options between tests.
I prioritized backwards compatibility (ensuring no existing tests need modification) over code neatness. It might be worth changing the flags to have --skip-notebook-name similar to --skip-tags to make them more consistent. Same with changing the `EOF` placement. But this would require changing tests.
=> Add include-notebook-name option

src/utils/templates/match-all.ts, src/utils/templates/remove-functions/remove-placeholder.ts
Yarle did not remove an unused template block, because I was using a template with Linux linefeeds under Windows.
It really should not matter which kind of EOL is in the template, i.e. you should be able to use a template with LF on Windows and vice versa a template with CRLF on Mac and Linux as well.
=> Templates should work on all platforms

README.md
Run npx with `@latest` because otherwise users may run an older version
from the npm cache that they had installed earlier.
=> Improve execution instructions in README

package-lock.json, package.json, src/utils/content-utils.ts, test/utils.spec.ts
Use "utimes" to set the creation time of the created Markdown files,
using the creation time of the correspondihg note in Evernote.
Of course the operating system and file system must support this.
Works perfectly on Windows, where creation date is supported.
On Linux, it should work as before.
This should solve #127.
=> Set creation time of Markdown files if possible

src/utils/turndown-rules/code-block-rule.ts
This PR is an attempt at solving #128.
The idea is to find blocks that are set in monospaced fonts only, and convert them into code fences.
It turned out that this is actually pretty difficult. The font can be set alternatively with "font face" or "font-family" in Evernote, and it could be overridden in deeper nested tags. Also we want to combine adjacent one-liner code blocks of this kind into a single one. We also do not want lines with mixed fonts, i.e. where only part of the line is monospace, to be interpreted as code blocks.
My PR tries to solve all of these issues, that's why it became a bit complicated.
There should be also tests and it should be optional behind a setting, but I haven't enough time to work on this. But I hope this PR at least can give an idea how to solve this.
=> Create code fences from monospace font sections

README.md, config.json, src/YarleOptions.ts, src/convert-to-html.ts, src/models/MetaData.ts, src/models/NoteData.ts, src/process-node.ts, src/process-resources.ts, src/utils/content-utils.ts, src/utils/file-utils.ts, src/utils/folder-utils.ts, src/utils/templates/apply-functions/apply-original-template.ts, src/utils/templates/apply-functions/index.ts, src/utils/templates/placeholders/original-placeholders.ts, src/utils/templates/templates.ts, src/yarle.ts
closes: https://github.com/akosbalasko/yarle/issues/81
This PR tries to implement the feature requested in #81.
When the new setting `keepOriginalHtml` is set to true, then for every Markdown file that is created, an HTML file will also be created in the `_resources` folder which is an exact copy of the original note in Evernote (pretty similar to what the Evernote client exports when you choose HTML format instead of ENEX).
I have also added a new template block `link-to-original` that allows adding a link to the original HTML in the Markdown file.
This makes the decision easier to ditch Evernote completely, because you don't need to fear losses in the  conversion from HTML to Markdown if you can always view the original in case of doubt. Also, in some cases the original formatting may …
=> Add an option to keep the original HTML

src/convert-html-to-md.ts, src/utils/turndown-rules/internal-links-rule.ts
See issue #140 for the problem I'm trying to solve here.
First tried calling JSDOM with a contentType of `text/xml` or `application/xhtml+xml`. This solved the issue, but then there were error messages complaining about "unknown entities" when the notes contained named entities such as `&nbsp;`.
So I solved the problem with a simple replacement of self-closing anchor tags, adding an explicit closing tag.
Maybe there are better solutions. We should probably also add a unit test.
Note that the change to `internal-links-rule.ts` is really simple: Return an empty string instead of  `undefind` when there is no `href` attribute. This removes the `undefined`, but would still swallow text without the fix in `convert-html-to-md.ts`.
=> Fix a problem with self-closing anchor tags (#140).

src/utils/turndown-rules/span-rule.ts
The `-evernote-highlight` must not always be the last CSS property.
=> Highlights were not always recognized properly

src/utils/filename-utils.ts
Because the 12 hour time is ambiguous without am/pm.
=> Use 24 hour time instead of 12 hour time for the Zettelkasten ID

src/utils/turndown-rules/images-rule.ts
Obsidian does not support the double-bracket notation for external images.
If the source URL is prefixed with a scheme, we need to use standard Markdown.
=> Use double-bracket notation only for local images

src/convert-to-html.ts
The regex to fix the image sources in the HTML output should be a global one.
=> Do not only fix the first image in the HTML output

src/process-node.ts, src/utils/templates/default-template.ts, src/yarle.ts, test/data/test-imageWithoutSrc.md, test/data/test-noteWithSourceUrl.enex, test/data/test-noteWithSourceUrl.md, test/data/test-webclip_article.md, test/data/test-webclip_bookmark.md, test/data/test-webclip_screenshot.md, test/data/test-webclip_simplifiedarticle.md, test/utils.spec.ts, test/yarle.spec.ts
In this case, xml-flow collapses the note-attribute sub-tag which will cause the corresponding note-attribute to be missing.
Fixed this edge-case and added a test spec "note with only source url". Without the change in `yarle.ts`, the test will fail.
Also added source-url to the default template, because I think the source URL is always important when there is one.
=> Fix issue when there is only one note-attribute

README.md, src/YarleOptions.ts, src/process-resources.ts, src/utils/turndown-rules/images-rule.ts
I added support to preserve an image's width and height on converted notes.
One option was to use raw HTML and keep the parameters, but it didn't feel right to use HTML in markdown. 
Thankfully Obsidian supports specifying an image's size by using the regular markdown image notation with a small twist, [e.g. here](https://forum.obsidian.md/t/0-9-7-resized-image-size-is-not-absolute/7728).
I also added a flag to enable this `keepObsidianImageSize`.
Hope this is useful to more people 😄
=> Support keeping image size

README.md, src/YarleOptions.ts, src/process-resources.ts, src/utils/folder-utils.ts
I added a `haveEnexLevelResources` option, so resources for a given enex
can be stored on the same folder, as mentioned on https://github.com/akosbalasko/yarle/issues/164.
To make this work, I had to count resource folder clears, so as ensure
the global enex-level resource folder isn't systematically deleted each time a note's
resources are processed.
=> feat: support having enex-level resource folders

src/utils/turndown-rules/index.ts, src/utils/turndown-rules/strikethrough-rule.ts, src/utils/turndown-service.ts, test/data/test-strikethrough.enex, test/data/test-strikethrough.md, test/yarle-tests.ts
Convert EN `<s>strike</s>` to `~~strike~~` rather than `~strike~`,
for compatibility with Obsidian and Joplin. (GFM allows either.)
Fixes #282
=> fix: convert strikethrough using `~~` rather than `~`

README.md, src/YarleOptions.ts, src/utils/folder-utils.ts, src/yarle.ts, test/data/test-withPicture-customResourcesDir.md, test/yarle-special-cases.spec.ts
Allow customizing subdir for attachments (default `_resources`).
This PR adds (and documents and tests) a new `resourcesDir` config option to permit using a directory like `_attachments` rather than `_resources`.
(The PR does not expose the new option in the Electron UI.)
=> feat: add `resourcesDir` config option

README.md
If folks are less familiar with Linux or not paying close attention (like I was today :sweat_smile:), these download options will be confusing to them. The link under Debian is for Debian and derivatives, which includes Ubuntu and thus most desktop Linux distros. Linux links to an `.rpm`, which works for Fedora, CentOS, and RHEL. 
I'm offering a minor annotation to acknowledge that without too much explanation.
=> Clarification of binary package type

src/dropTheRope.ts
Not every system have `node` installed in `/usr/local/bin`. It can be in `/usr/bin`, or for people using `n` or `nvm`, it will be in their home directory.
Using `env` to find an interpreter is a common thing in scripts, and will resolve this issue.
=> Use 'env' to find 'node' interpreter path

src/process-node.ts, src/process-resources.ts, test/data/test-image-dataUrl.enex, test/data/test-image-dataUrl.md, test/yarle-special-cases.spec.ts
Extract the data url from `<img src="data:...">` into resources,
and patch up the src.
(EN 10's web clipper uses data urls for SVG images.
This change should handle any `src="data:..."` for any
media types.)
=> fix: extract resources from data urls

README.md, src/YarleOptions.ts, src/utils/filename-utils.ts, src/utils/turndown-rules/images-rule.ts
Recently, I faced the issue of finding broken image links on my Obsidian test export. These were broken because they had spaces in them.
After looking a bit around, I found that I could use `urlEncodeFileNamesAndLinks` and that that was in fact the [standard markdown approach](https://forum.obsidian.md/t/markdown-image-links-failing-for-filenames-with-whitespace/943).
However, enabling `urlEncodeFileNamesAndLinks` renames all my note in a way that makes them harder to find and reason about. Consequently, I thought the best approach would be to simply remove spaces from resource names, as regular links work fine with spaces.
In my approach, I added a `sanitizeResourceNameSpaces` flag and applied this transform both on the filename-utils side and on the image-rules, so the links would …
=> feat: Sanitize spaces from resources names

src/utils/turndown-rules/span-rule.ts, test/data/test-imageWithoutSrc.md
Some of my notes were missing bold conversion when targeting `ObsidianMD`. After digging a bit, I noticed this conversion had been implemented in the context of https://github.com/akosbalasko/yarle/pull/302.
I enabled that change to cover all formats, as I believe this kind of conversion is useful for all target formats. Doing this solved my bold conversion issues.
=> feat: support bold conversion on all formats

src/utils/filename-utils.ts
Recently, I noticed a couple of my test notes had a number suffix, as if
they shared the exact same name as another note when that wasn't the case.
I patched the way file collisions are detected, so the first would-be
literal collision is detected and handled while being able to count subsequent avoided collisions.
I hope this is helpful :)
=> fix: filename collisions

README.md, src/YarleOptions.ts, src/utils/folder-utils.ts
Added support for global resource folders (related to https://github.com/akosbalasko/yarle/issues/263).  This seems to make a lot of sense with Obsidian in particular. Instead of only supporting Obsidian, I opened the feature to other conversion targets.
I added a new option `haveGlobalResources`. I am wondering if this is the best approach given we already have `haveEnexLevelResources`, but I stuck with it for retrocompatibility reasons.
I tested this with local note resources, ENEX-level and global resources.
Hope this is helpful!
=> feat: Support global resource folders

src/utils/filename-utils.ts
I noticed some of my note attachments weren't getting converted due to either having `[]` or `+` in their filename.
I replaced those chars to tackle this :)
=> fix: Replace brackets and plus sign on filenames

src/utils/turndown-rules/images-rule.ts
I noticed Obsidian images got broken due to https://github.com/akosbalasko/yarle/pull/326. This should now be fixed
👍
=> Fix: Obsidian image sizes

src/convert-html-to-md.ts
This PR is two-fold and it covers two different aspects in pre-parsing
an en-note before converting it
* It fixes `en-todo` wrapping:
* `[[] foo](bar)` -> `[] [foo](bar)`
* `*[] foo*` -> `[] *foo*`
* It fixes losing content on nested lists (for older Evernote versions) following the approach
described in https://github.com/akosbalasko/yarle/issues/324#issuecomment-986269013. I further narrowed the check, so as not to break the tests
=> Fix: en-todo wrapping and content lost on nested lists

src/utils/turndown-rules/task-items-rule.ts, test/data/test-empty-en-todo.enex, test/data/test-empty-en-todo.md, test/yarle-tests.ts
story: https://github.com/akosbalasko/yarle/issues/416
=> fix: empty en-todo fixed

src/YarleOptions.ts, src/ui/settingsMapper.ts, src/utils/filename-utils.ts, src/utils/templates/apply-functions/apply-tags-array-template.ts, src/utils/templates/checker-functions.ts, src/utils/templates/templates.ts, src/utils/turndown-rules/task-list-rule.ts, test/data/test-checkboxes.enex, test/data/test-checkboxes.md, test/data/test-checklist.enex, test/data/test-checklist.md, test/yarle-tests.ts
story: https://github.com/akosbalasko/yarle/issues/437
=> feat: support of v10.48 todos implemented

src/ui/main.js
I was getting an error like this on the commmandline:
~~~
(node:911326) UnhandledPromiseRejectionWarning: ReferenceError: applyLinks is not defined                                                                                            
at IpcMainImpl.<anonymous> (/home/~/Source/Clones/yarle/dist/ui/main.js:71:7)                                                                                                
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)                                                                                                    
(Use `electron --trace-warnings ...` to show where the warning was created)                                                                                                          
(node:911326) …
=> fix:Reference Error in UI Log

Notes_for_Logseq.md, README.md, config.json, config.logseq.json, config.tana.json, package-lock.json, package.json, src/YarleOptions.ts, src/ui/index.html, src/ui/settingsMapper.ts, src/utils/apply-links.ts, src/utils/filename-utils.ts, test/data/test-levenshtein-links.enex, test/data/test-levenshtein-linksNoteA.md, test/data/test-levenshtein-linksNoteB.md, test/yarle-special-cases.spec.ts
story: https://github.com/akosbalasko/yarle/issues/531
=> feat: levenshtein distanced links implemented

src/ui/main.js, src/yarle.ts
BREAKING CHANGE: configs are saved as plain text, no base64 encoding
=> configs saved with timestamps

README.md, src/ui/index.html, src/utils/content-utils.ts
story: https://github.com/akosbalasko/yarle/issues/578
=> fix: cyrill tags fixed

src/utils/turndown-rules/internal-links-rule.ts
A more robust check in isEvernoteLink protects against invalid links getting into the link map, causing erronious text replacements in apply-links.ts. Previously, all links starting with "https://www.evernote.com" were incorrectly assumed to be note links, now those links are better identified by an expected note link format, while other evernote.com links will be correctly treated as regular web links.
=> fix: Invalid note links breaking other links during replacement (#487)

src/utils/turndown-rules/internal-links-rule.ts
story: https://github.com/akosbalasko/yarle/issues/487
=> fix: Invalid note links breaking other links during replacement

src/utils/apply-links.ts, test/data/two-untitled-notes-with-toc.1.md, test/data/two-untitled-notes-with-toc.enex, test/data/two-untitled-notes-with-toc.md, test/yarle-special-cases.spec.ts
story: https://github.com/akosbalasko/yarle/issues/609
=> fix: unrecognized guid/links added

src/models/NoteData.ts, src/outputLanguages/StandardMD.ts, src/process-resources.ts, src/utils/content-utils.ts, src/utils/filename-utils.ts, src/utils/folder-utils.ts, src/utils/save-html-file.ts, src/utils/save-md-file.ts, test/utils.spec.ts
=> fix: timestamp of MD file
